source "https://rubygems.org"

gem "awesome_print"
gem "dotenv"
gem "faraday"
gem "jwt"
gem "pry-nav"
gem "oj"
gem "puma"
gem "sequel"
gem "sequel_pg"
gem "sequel_secure_password"
gem "rake"
gem "roda"

group :development, :test do
  gem "database_cleaner-sequel"
  gem "factory_bot"
  gem "rspec"
  gem "rubocop"
  gem "solargraph"
  gem "super_diff"
  gem "swagalicious"
end
