source "https://rubygems.org"

gem "awesome_print"
gem "dotenv"
gem "jwt"
gem "pry"
gem "puma"
gem "rake"
gem "roda"

group :development, :test do
  gem "database_cleaner-sequel"
  gem "factory_bot"
  gem "rspec"
  gem "rubocop"
  gem "super_diff"
  gem "swagalicious"
end

group :postgres do
  gem "sequel"
  gem "sequel_pg"
end

group :json do
  gem "oj"
end
