FROM node:18.7-alpine as builder

WORKDIR /usr/src/app

COPY frontend/ .

RUN yarn install && yarn build

FROM nginx:alpine
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
# Copy static assets from builder stage
COPY --from=builder /usr/src/app/build .
COPY docker/nginx_default.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
